### ISSUE TITLE
Fix dragonfly event warning IPAddressWrongReference

### ISSUE THREAD

**Issue by tscibilia** [tscibilia/home-ops#236]
### IPAddressWrongReference
IPAddress: 10.43.107.81 for Service database/dragonfly-cluster has a wrong reference; cleaning up

This occurs 2-3 times per hour

**Comment by tscibilia** [comment]
ChatGPT tells me I need to add a `Post-Sync Job` to patch `IPAddresses`

Patch each new IPAddress with an ownerReference. You could add a Flux post-sync hook that runs a small kubectl patch Job after every reconciliation. This job runs after every Flux sync, discovers any IPs for your Service, and patches them. It’s a bit hacky but does live in GitOps.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-dragonfly-ip
  namespace: flux-system
  annotations:
    fluxcd.io/hook: post-sync
    fluxcd.io/hook-weight: "5"
spec:
  template:
    spec:
      serviceAccountName: flux-job-sa
      restartPolicy: Never
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          UID=$(kubectl get svc dragonfly-cluster -n database -o jsonpath='{.metadata.uid}')
          for ip in $(kubectl get ipaddress -A \
                        --no-headers \
                        | awk '/database\/dragonfly-cluster/{print $2}'); do
            kubectl patch ipaddress $ip \
              --type=merge \
              -p "{\"metadata\":{\"ownerReferences\":[{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"name\":\"dragonfly-cluster\",\"uid\":\"${UID}\"}]}}"
          done
```
