### ISSUE TITLE
Fix rook-ceph-mgr serviceMonitor TargetDown issue

### ISSUE THREAD

**Issue by tscibilia** [tscibilia/home-ops#245]
Victoria Metrics Agent is logging issues with `rook-ceph-mgr-external` being 2/3 down. 

Rook-Ceph's service monitor `rook-ceph-mgr` is recreated exactly by VMScrapeMonitor CD and causes these errors. 

Looked into the possibility of patching it but it didn't work, so I might need to just use my own version based on this https://github.com/rook/rook/raw/refs/heads/master/deploy/examples/monitoring/service-monitor.yaml

```yaml
spec.chart.values:
  postRenderers:
    - kustomize:
        patches:
          # ── 1) Patch the Prometheus Operator ServiceMonitor ────────────────
          - target:
              group: monitoring.coreos.com
              version: v1
              kind: ServiceMonitor
              name: rook-ceph-mgr
            patch: |
              - op: add
                path: /spec/endpoints/0/relabelings
                value:
                  - sourceLabels: ["__meta_kubernetes_endpoint_address"]
                    regex: "10\\.10\\.10\\.[23]"
                    action: drop
```
